---
- name: make sure needed software is installed
  yum: 
    name: yum-utils
- name: remove old kernel packages for RPM based systems
  shell:  package-cleanup -y --oldkernels --count='{{ os_update_keep_kernel_nr }}'
  register: cmd
  changed_when: "'Nothing to do' not in cmd.stdout"
...
