---
- name: make sure needed software is installed
  dnf: 
    name: yum-utils
- name: remove old kernel packages for RPM based systems
  shell:  dnf remove -y $(dnf repoquery --installonly --latest-limit=-'{{ os_update_keep_kernel_nr }}' -q)
- name: remove old kernel packages for RPM based systems
  shell: |
    RUNNING_KERNEL=$(uname -r)
    # echo RUNNING_KERNEL=$RUNNING_KERNEL
    # echo INSTALLED_KERNELS
    # rpm -q kernel kernel-core
    dnf remove --oldinstallonly --setopt installonly_limit='{{ os_update_keep_kernel_nr }}' -y
  register: cmd
  changed_when: "'Nothing to do' not in cmd.stdout"
...
