---
- name: test if linux host is alive
  block:
  - name: 1st ping linux
    ping:
    register: ping
    failed_when: false

  - name: 2st ping linux
    ping:
    register: ping2
    failed_when: false
    when: ping.failed
  when: (ansible_connection is defined) and ((ansible_connection == 'ssh') or (ansible_connection == ''))

- name: test if windows host is alive
  block:
  - name: 1st ping windows
    win_ping:
    register: ping
    failed_when: false

  - name: 2st ping windows
    win_ping:
    register: ping2
    failed_when: false
    when: ping.failed
  when: (ansible_connection is defined) and (ansible_connection == 'winrm')

- name: finally, we decide to proceed
  setup:
  when: ping.failed == false or ping2.failed == false

...
