---
- name: apply security windows updates
  win_updates:
    category_names: "{{ os_update_windows_updates_category_names_security }}"
    reboot: "{{ os_update_reboot }}"
    reject_list: "{{ os_update_windows_updates_reject_list }}"
  register: win_updates

- name: display update results
  debug:
    var: win_updates
...
