---
- name: install needed packages
  dnf:
    name:
    - yum-utils
    - python3-dnf
    state: present
- name: install security patches
  dnf:
    name: '*'
    state: latest
    update_cache: True
    security: yes
...
